package com.mountbirch.javatest;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class WriteSomeTestsApplicationTest {

    @Test
    void contextLoads() {
        // This is auto-generated by Spring Initializer and there is no need to modify it.
    }

}
